### ISSUE TITLE
Hi, i'm using hp 8540p with Nvidia nvs5100, can u support for the 1st gen laptop?

### ISSUE THREAD

**Issue by duonganhhung** [chris1111/HP-Probook-EliteBook-Package-Creator#1]
Hi, i'm using hp 8540p with Nvidia nvs5100, can u support for the 1st gen laptop ?
Thx :)

**Comment by chris1111** [comment]
> Hi, i'm using hp 8540p with Nvidia nvs5100, can u support for the 1st gen laptop ?
> Thx :)

No sorry because the first gen arandale CPU needs a patch kext but you can find a way here to make it work. https://www.insanelymac.com/forum/topic/286092-guide-1st-generation-intel-hd-graphics-qeci/?hl=%2Bintel%20%2B1st%20%2Bgen%20%2Bgraphics&page=1
