### ISSUE TITLE
Installation went good, but post issues with USB ( Elitebook 8460p Mojave )

### ISSUE THREAD

**Issue by flow711** [chris1111/HP-Probook-EliteBook-Package-Creator#11]
Hey,
i have the following problem, that only 1 USB port is working, its the one on the right side where the DisplayPort and the Sata port is. Do you have a solution for this ? or a Fix ? 
Next problem is the Appstore, I can't login gives me a  Com.apple.commerce.client-fault 500
Thx for you're Project :)

Mac OS Mojave 
HP Elitebook 8460p with Intel HD 3000 Graphics

Greets

**Comment by chris1111** [comment]
> Hey,
> i have the following problem, that only 1 USB port is working, its the one on the right side where the DisplayPort and the Sata port is. Do you have a solution for this ? or a Fix ?
> Next problem is the Appstore, I can't login gives me a Com.apple.commerce.client-fault 500
> Thx for you're Project :)
> 
> Mac OS Mojave
> HP Elitebook 8460p with Intel HD 3000 Graphics
> 
> Greets

Ok for Appstore try to create a different SMBIOS maybe a MacBook Air ?
For USB try to put  in Clover/kexts/10.14/USBInjectAll.kext
[USBInjectAll.kext.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator/files/2824810/USBInjectAll.kext.zip)

**Comment by flow711** [comment]
Hmm Appstore not working with Macbook air smbios, and after inserting USB kext it's not anymore booting the system up...

**Comment by chris1111** [comment]
ok block kext by clover option
remove the kext and try to use USBGeneric
https://bitbucket.org/RehabMan/os-x-generic-usb3/downloads/

**Comment by flow711** [comment]
Great. Works now. So now the only problem is the Appstore... Drives me crazy xD. But many many Thx for your help.

**Comment by flow711** [comment]
But it shows only USB 2.0 systeminformations.

**Comment by chris1111** [comment]
Take a look here
let me know if that help
https://discussions.apple.com/thread/8644593

**Comment by flow711** [comment]
USB port are unstable now, random disconnects but only at the USB 3 ports on right side.

**Comment by chris1111** [comment]
> USB port are unstable now, random disconnects but only at the USB 3 ports on right side.

Post here the complet EFI Folder on ZIP

**Comment by flow711** [comment]
[https://ufile.io/fv6bu(url) here is it

**Comment by chris1111** [comment]
Remove GenericUSBXHCI.kext

Change DSDT.aml by the one attaching here
EFI/CLOVER/ACPI/patched/DSDT.aml
[DSDT.aml.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator/files/2825045/DSDT.aml.zip)

Reboot the laptop

**Comment by flow711** [comment]
not working with the dsdt , its late I need to sleep now. thanks for you're help I write you later again :)

**Comment by chris1111** [comment]
> not working with the dsdt , its late I need to sleep now. thanks for you're help I write you later again :)

try this one
[DSDT.aml.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator/files/2825054/DSDT.aml.zip)

**Comment by flow711** [comment]
Also not working. Laptop don't like MacOS 😃.

**Comment by flow711** [comment]
Appstore is now working.

**Comment by chris1111** [comment]
Laptop HP like macOS you have the prouve, only USB issue that's not a big deal 😃.

try this kexts in Clover and reboot
[mXHCD.kext.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator/files/2825576/mXHCD.kext.zip)

**Comment by flow711** [comment]
Yea you're right 😆 so now the usb is showing up again but random disconnects..

**Comment by flow711** [comment]
i5 2540m , will test now .

**Comment by flow711** [comment]
not working 😞

**Comment by chris1111** [comment]
when you using the ProBook Installer he will not create a SSDT.aml with your CPU and the MacBook Pro System definition, I see on your EFI SSDT is missing
So you have to put this file in patched
this is the SSDT you need for your Power Management i5 2540m
[SSDT.aml.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator/files/2825615/SSDT.aml.zip)

**Comment by flow711** [comment]
nice, you're right, cpu only clocking from 2,7 ghz to 3 ghz 😄

**Comment by chris1111** [comment]
> nice, you're right, cpu only clocking from 2,7 ghz to 3 ghz 😄

You have to stay with the MacBook Air 5.1 and all is good

**Comment by flow711** [comment]
only the usb bug, annoying

**Comment by chris1111** [comment]
> yea had test it, and not working :(

Try this one with the kext and without the kext
[DSDT.aml.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator/files/2825648/DSDT.aml.zip)

**Comment by flow711** [comment]
with and without not working, with kext random disconnects, without usb it not showing up

**Comment by chris1111** [comment]
I think this issue is relate to Mojave because with High Sierra or Sierra that's not an issue with this HP laptop model

**Comment by flow711** [comment]
so we can't fix it properly ?

**Comment by chris1111** [comment]
> so we can't fix it properly ?

I try everything is possible in my knowledgement

**Comment by chris1111** [comment]
> could this appear because of my bios version ? I have the newest one I think o.o

maybe yes?

**Comment by flow711** [comment]
lol, just lol. it was impossible to downgrade the bios, so my last idea was CLEAR THE BIOS SETTINGS .......... Hate xD Thx for you're help Mr, you are a Hero for all you're help.

**Comment by flow711** [comment]
its working now , but I inserted the generic kext

**Comment by chris1111** [comment]
> its working now , but I inserted the generic kext

Good to know 👍 I close issue
