### ISSUE TITLE
Issue with Speedstepping 

### ISSUE THREAD

**Issue by flow711** [chris1111/HP-Probook-EliteBook-Package-Creator#12]
Hey Mr,

8 Days ago we solved my USB problem, but now it seems there is another "problem". Its my CPU Powermanagement, the CPU is running all the time with the Highest Pstate , also with youre SSDT. 
I created a new one with ssdtPRGen, but then the CPU locks at 800 mhz. Then i created another one with this tool but slightly different and then it runs again permanently at highest Pstate .. I hope you can help me :)

**Comment by chris1111** [comment]
> Hey Mr,
> 
> 8 Days ago we solved my USB problem, but now it seems there is another "problem". Its my CPU Powermanagement, the CPU is running all the time with the Highest Pstate , also with youre SSDT.
> I created a new one with ssdtPRGen, but then the CPU locks at 800 mhz. Then i created another one with this tool but slightly different and then it runs again permanently at highest Pstate .. I hope you can help me :)

You can try this config here
[config.plist.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator/files/2853855/config.plist.zip)

**Comment by flow711** [comment]
Sadly not working, same as before

**Comment by chris1111** [comment]
> Sadly not working, same as before

Try this to generate SSDT
[Generate SSDT DSDT.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator/files/2871977/Generate.SSDT.DSDT.zip)

**Comment by chris1111** [comment]
Ok try to generate SSDT with this

[Generate SSDT DSDT.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator/files/2896937/Generate.SSDT.DSDT.zip)

**Comment by chris1111** [comment]
If you find a solution please post here the result
thanks
I will close this issue
