### ISSUE TITLE
HP Probook 4740s Post Install Issues

### ISSUE THREAD

**Issue by waylonh** [chris1111/HP-Probook-EliteBook-Package-Creator#13]
Hi Chris,

First off, I want to thank you for the immense amount of work you've done with regards to getting HP laptops to work with MacOS! I've followed countless tutorials to try to get High Sierra or Mojave to work without success until I found your Installer, it worked like a bomb!

The issue I'm having is this...
After a clean install with Mojave using your installer, I run your post package app, select the settings as per your youtube video showed but for my model and settings (7 series, Intel HD3000 1600x900, etc), restart the laptop but nothing changes when logging back in, except for "Bootchimedxe" which now plays the Mac startup sound and the battery Icon now shows up in the top taskbar.

It's as if none of the settings from the package work after rebooting.
Video still set to 1024x768 (can't change this)
No Audio (no devices detected)
No Wifi (this I know may be due to needing another kext not supplied in your package since my wifi is AR9485 and not AR9285)
HWMonitor looks to be working but Im not sure if the temps are correct.

Any idea what I may need to do to resolve the Audio and Video Resolution and possibly the WiFi?

My Specs are as follows...
HP Probook 4740s (Mobile Intel HM76 chipset)
Intel Core i5-2450m
Intel HD 3000 + AMD Radeon HD 7650M (Disabled in Bios)
17.3 HD 1600x900 Display 
8GB RAM
120GB Samsung EVO SSD
2nd 700GB 5400RPM HDD (in the optical drive bay)
Atheros AR9485 WiFi Card
Realtek RTL8111 NIC
HD Audio (Intel Panther Point HDA Controller 8086/1E20 as per what clover says)

Kind regards,

**Comment by chris1111** [comment]
Thanks Waylon

MacOS Mojave not support Intel HD 3000 
The patch support MacOS Mojave 10.14.2 
Apple broken the support after 10.14.2
So you have to used 10.14.2 if you have it or retry full Install with High Sierra 10.13 or Sierra 10.12 but don’t used the Intel HD 300 Mojave patch for High Sierra, High Sierra support HD 3000 and the DSDT doing be the job for this.

For the Atheros AR9485 The patches for it are complex, poorly documented, and not provided in a Clover KextsToPatch format.
It means that each revision will require a new patched kext to be created, etc.
Not recommended...

Much easier to install compatible WiFi with well documented patches or native support.

**Comment by waylonh** [comment]
Ahh ok, no wonder, Im using 10.14.3.
I'll try to install using Mojave 10.14.2 failing that I'll try High Sierra.
Noted on the WiFi card, I'll try to find one on ebay that's compatible!

Thanks again for everything, once again, you do amazing work!

**Comment by chris1111** [comment]
> Ahh ok, no wonder, Im using 10.14.3.
> I'll try to install using Mojave 10.14.2 failing that I'll try High Sierra.
> Noted on the WiFi card, I'll try to find one on ebay that's compatible!
> 
> Thanks again for everything, once again, you do amazing work!

For WIFI try to buying
WIFI Broadcom BCM943224hms with the AirportBrcmFixup Fix

**Comment by waylonh** [comment]
Fantastic!
Found that exact wifi card on Ebay for $5!
Thanks again! 👍
