### ISSUE TITLE
How to Install Kext for JMicron Card Reader

### ISSUE THREAD

**Issue by ngdanghau** [chris1111/HP-Probook-EliteBook-Package-Creator#14]
Hi, I install macOS Seirra on my HP8460p, and how to Install Kext for JMicron Card Reader on it? it's available on DPCIManager
![Screen Shot 2019-03-28 at 11 34 31 PM](https://user-images.githubusercontent.com/33993567/55175537-12072f00-51b2-11e9-8679-9684b76c2be9.png)

**Comment by chris1111** [comment]
the kext is in Clover EFI/CLOVER/kexts//10.12
[![Modular Image Creation](https://i25.servimg.com/u/f25/18/50/18/69/captu569.png)

**Comment by ngdanghau** [comment]
i think it dont work.

**Comment by chris1111** [comment]
> i think it dont work.

I don't know what's wrong with you on 10.12 ? its work here 10.13 and 10.14

**Comment by ngdanghau** [comment]
I have a SD Sand Disk of Canon Camera, i insert it to computer and nothing happened .

**Comment by chris1111** [comment]
upload EFI folder here

**Comment by ngdanghau** [comment]
It here:
https://drive.google.com/open?id=1nI_wqPlhXr-Winkwjn7UPgmNoTFwpjVA

**Comment by chris1111** [comment]
I don't know what's wrong with you ? ?
You can try to install the kext in the system ?

Copy both kext **JMB38X.kex / HSSDBlockStorage.kext** in Desktop
then remove the kext on Clover /  kexts / 10.12 

Try to install the kext in **S/L/E** WITH this utility
https://github.com/chris1111/Kext-Droplet

**Comment by ngdanghau** [comment]
it still doesn't work

**Comment by chris1111** [comment]
> it still doesn't work

So delete the both kext in S/LE

I see on your EFI some kext not comes from the HP ProBook EliteBook macOS
maybe one of them is causing you this problem ?

[![Modular Image Creation](https://i25.servimg.com/u/f25/18/50/18/69/captu570.png)

**Comment by ngdanghau** [comment]
It work when i insert SD before boot macos =)), insert after macos booted is don't work

**Comment by chris1111** [comment]
> It work when i insert SD before boot macos =)), insert after macos booted is don't work.
> And i have a problem with restart. When I click restart it show black screen not restart. Can you fixed it?

Complete a fresh install of Sierra with the latest Program here ➣ https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator/releases/tag/V2

With your config the only issue is about USB 3  maybe ?
If you have issue about USB telling me what not work, and don't install kext in Clover

**Comment by ngdanghau** [comment]
Yes, USB 3 of my computer is not working, so I install GenericUSBXHCI.kext and it work when insert USB before boot macos, it quite inconvenient

**Comment by chris1111** [comment]
>  I will try fresh Sierra.

Ok and don't use USBGeneric
telling me when you have done

**Comment by ngdanghau** [comment]
while install, Can you help me fixed facetime and imessage ? p/s: I have a real info macbook, it maybe helpful.

**Comment by chris1111** [comment]
Not need real macBook to do this, when you have done send me EFI

**Comment by chris1111** [comment]
I will see your EFI tomorrow morning, I go to sleep

**Comment by ngdanghau** [comment]
Here: https://drive.google.com/open?id=189v8zvqgbKprxUack8mIgSLMn_dr6X7n
But I done, I found many issue:
1. Sound play before boot apple logo (different creator V1)
2. No Ethernet (different creator V1)
3. USB 3.0 not working (same creator V1)
4. SD Reader not working (same creator V1)
5. Restart Woking.

**Comment by chris1111** [comment]
1- Sound play before boot apple logo (Normal its new boot chime like a real Mac)

2- Ethernet (Try the kext IntelMausiEthernet.kext  V-2.4.1d1) attaching here change on 10.12
[IntelMausiEthernet.kext.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator/files/3025416/IntelMausiEthernet.kext.zip)

3- USB 3.0 (Try This program) here https://github.com/chris1111/USB-3.0-NEC/releases

4- SD Reader I will check after

**Comment by ngdanghau** [comment]
Thanks for all, it work and how to active imessage and facetime ?

**Comment by chris1111** [comment]
> Thanks for all, it work and how to active imessage and facetime ?

Mount EFI Partition and Copy config.plist to your desktop

open config with Clover configurator

Click Generate
[![Modular Image Creation](https://i25.servimg.com/u/f25/18/50/18/69/captu572.png)

Click Generate
[![Modular Image Creation](https://i25.servimg.com/u/f25/18/50/18/69/captu573.png)

Save and replace in EFI REBOOT

**Comment by ngdanghau** [comment]
When I reboot done, i login imessage i found issue:
![Screen Shot 2019-03-30 at 11 59 29 PM](https://user-images.githubusercontent.com/33993567/55279173-11a09c80-5348-11e9-9b15-a9e089b64052.png)

**Comment by chris1111** [comment]
Open terminal paste this on terminal follow by Enter
**UUIDGEN**
Copy the code UUIDGEN
[![Modular Image Creation](https://i25.servimg.com/u/f25/18/50/18/69/captu574.png

Copy paste the code on clover configurator 
[![Modular Image Creation](https://i25.servimg.com/u/f25/18/50/18/69/captu575.png)

**Comment by ngdanghau** [comment]
It don't work

**Comment by chris1111** [comment]
> It don't work

Try UUIDGEN and generate Serial Number

**Comment by ngdanghau** [comment]
I try many times but still have same issue

**Comment by chris1111** [comment]
> I try many times but still have same issue

Try this
[config.plist.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator/files/3026151/config.plist.zip)

**Comment by ngdanghau** [comment]
Still don't work

**Comment by chris1111** [comment]
> Still don't work
Sorry but I am not understand
