### ISSUE TITLE
HP Pavilion Gaming 15 support?

### ISSUE THREAD

**Issue by arno608rw** [chris1111/HP-Probook-EliteBook-Package-Creator#15]
Hi @chris1111 ---> HP Pavilion Gaming 15 support?

> 
Brand | HP
-- | --
Model | Pavilion power 15-cb527TX
Processor | Intel Core i7-7700HQ 2.8GHz (6 MB cache, 4 cores Up to 3.8 GHz )
Chipset | Intel SOC Chipset
Graphics | NVIDIA GeForce GTX 1050 (4GB GDDR5)
Display Screen | 15.6" diagonal FHD IPS anti-glare WLED-backlit (1920 x 1080)
Main Memory | 4GB DDR4 2400MHz
Memory Slot | 2 x Slots
Max Memory | 16GB
Hard Drive | 1TB 7200rpm
Web Camera | HP Wide Vision HD Camera HP Wide Vision FHD IR Camera Dual array digital microphone
Sound Technology | B&O Play HP Audio Boost 1 x Headphone/Microphone Combo
Audio Jack | 1 x Headphone/Microphone Combo
Speaker | Dual speakers
Network | 10/100/1000 LAN
Wireless | Wireless 802.11a/b/g/n/AC
Bluetooth | Bluetooth 4.2
Port | 1 x HDMI 1 x USB 3.1 Type-C™ (HP Sleep and Charge, Data up to 5Gb/s, Display Port 1.2) 3 x USB 3.1 Gen 1 (1 HP Sleep and Charge)
CardReader | 1 x multi-format SD media card reader (support SD/SDHC/SDXC)
Power Adapter | 150 W AC power adapter
Battery | 4-cell, 70 Wh Li-ion polymer Support battery fast charge, Approximately 90% in 90 minutes9
OS | Windows 10 Home
Dimensions (W x D x H) | 378 x 252.2 x 24.1 mm
Weight | 2.18 kg
Keyboard Type | Full-size island-style backlit keyboard with numeric keypad
Backlit | Yes
Touchpad | HP Imagepad with multi-touch gesture support
Special Feature | Kensington MicroSaver® lock slot

**Comment by chris1111** [comment]
Sorry but this repository is only for ProBook laptop, all patch DSDT is only for HP Probook 
I have to close the issue
