### ISSUE TITLE
how to install high serrria on HP 4430s

### ISSUE THREAD

**Issue by at-tantv** [chris1111/HP-Probook-EliteBook-Package-Creator#16]
- I will build USB for install macos 10.13.I received error "No Support CPU"
- I3 2xxx,HD3000 

Help me..
Thanks you

**Comment by at-tantv** [comment]
I am create same as your video on youtube.
Now, i install MACOS 10.14 Mojave.
I installed success, but Intel Graphic HD3000 not receive driver.
Next, What should I do ?

**Comment by arno608rw** [comment]
You can install on new releases support HD3000

**Comment by chris1111** [comment]
Ok release is ready now

**Comment by at-tantv** [comment]
Thank you admin,thanks you everyone !
Now,　I will try install on v2

**Comment by at-tantv** [comment]
Mac high serria 
How can fix this error ?

**Comment by at-tantv** [comment]
[https://www.upsieutoc.com/image/k55jBq](url)

**Comment by chris1111** [comment]
> Mac high serria
> How can fix this error ?
> 
> IOControleUser gIOScreenLockState 3

https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator/issues/17#issuecomment-481823947

**Comment by at-tantv** [comment]
Thanks you
I remove bootchim
And remove audio...
I booted on high serria success
Now, i am installing

**Comment by at-tantv** [comment]
Now , i install 10.13 success
But not receive hd 3000
No wifi , no graphic , no LAN internet
Help me, Pleae

**Comment by chris1111** [comment]
You probably do not have to select the right options for the 4530s in the program, everything should work

**Comment by at-tantv** [comment]
I disabled Graphic, LAN Network and WIFI in BIOS.

*
