### ISSUE TITLE
HP Probook 4530s gioscreenlockstate 3 stuck!

### ISSUE THREAD

**Issue by bigboigahoy** [chris1111/HP-Probook-EliteBook-Package-Creator#17]
i3 variant. I boot into the installer and it freezes at gIOLOCKSCREENSTATE 3. I made the bootable from the tutorial in the video on the main page. Is this something that is caused by the bios not being on F50? If so I cannot find the F50 bios file online but the F67 (latest) which I saw that it must be on F50! Any links to the file?

**Comment by chris1111** [comment]
you can not roll Back bios on HP Laptop
For bypass this issue try fake id 0x00010000 under intel inject clover setting..

**Comment by bigboigahoy** [comment]
My bios isn't updated past f50 it's actually under it. I was trying to
figure out if updating the bios to f50 would fix this and where to find
this specific version for the probook 4530s. But when I get the chance I
will try to inject this fake id

**Comment by chris1111** [comment]
Bios is here on HP
https://support.hp.com/ca-fr/drivers/selfservice/hp-probook-4530s-notebook-pc/5060880

open the box  previous version 
see image

![Modular Image Creation](https://i25.servimg.com/u/f25/18/50/18/69/captu596.png)

**Comment by bigboigahoy** [comment]
I did what you said, updated the BIOS, and changed the config for the fake
id and it worked, thank you! One last thing, how do I turn off the boot
chime for clover?

**Comment by chris1111** [comment]
> I did what you said, updated the BIOS, and changed the config for the fake id and it worked, thank you! One last thing, how do I turn off the boot chime for clover?
> […](#)

Remove AudioDxe.efi and BootChimeDxe.efi on Drivers64UEFI

**Comment by bigboigahoy** [comment]
Thanks for all of the help, the only other thing that isn’t working is the
Camera. Is that something that is expected in this setup, or is there a
patch to get it working?

**Comment by chris1111** [comment]
camera suppose to work 
are you sure your not talk about FaceTime not activate ?

**Comment by bigboigahoy** [comment]
No, going into device manager there is no device for camera. I think there
is spotty support for the camera. The usb 3.0 doesn’t work (but the other
ones do. I think I just need a kext). Also is there’s a way to generally
reduce the amount of graphic glitches?

**Comment by chris1111** [comment]
USB fix  on this series you can try this 
https://github.com/chris1111/USB-3.0-NEC/releases
Graphics glitch HD 3000 it s know issue you can try ad boot args slide=0
It's very rare but I know there are some HP Probook cameras that are not supported maybe it's your? , do some research

**Comment by bigboigahoy** [comment]
Thanks for the information and help. Everything is working great, it was a
very seemless install for a laptop! Great work!
