### ISSUE TITLE
Can you please help me fix the graphics issue for Elitebook 8560p with Redeon HD 6470M?

### ISSUE THREAD

**Issue by Mtkhan13** [chris1111/HP-Probook-EliteBook-Package-Creator#19]
I have installed High Sierra on my laptop using your tool and when I boot from USB the display resolution and colors works fine but only show 5Mb of Graphic RAM. When I boot from SSD, resolution didn't work correctly also the Graphics RAM reduces to 3Mb. Can you please guide me how can I fix this problem.
Also wifi didn't work, it has a Broadcom wifi
Also Sound and battery works when booting SSD, not with USB.

I'm attaching a screenshot and my clover plist. I will look forward to your reply.

Thank you

![Screen Shot 2019-05-13 at 8 42 20 AM](https://user-images.githubusercontent.com/22547975/57741631-1f7f6680-76d7-11e9-8cb3-a13c2e896f04.png)
[config.plist.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator/files/3180479/config.plist.zip)

**Comment by chris1111** [comment]
AMD Radeon not work You have to disable it 
only Intel HD4000 will works

**Comment by Mtkhan13** [comment]
Will the older versions work? like Sierra or El Captian?

**Comment by Mtkhan13** [comment]
Also I'm not sure how to disable the AMD and as I don't see HD4000 or HD3000 in my laptop.

**Comment by chris1111** [comment]
> Will the older versions work? like Sierra or El Captian?

No the only Graphics card working is the IGPU
disable in Bios or select the right option in the program
