### ISSUE TITLE
Touchpad don't work on HP8460p

### ISSUE THREAD

**Issue by ngdanghau** [chris1111/HP-Probook-EliteBook-Package-Creator#20]
Hi. I have used macos for a month and now touchpad don't work? I don't know why, touchpad is still work on windows.

**Comment by chris1111** [comment]
On which macOS?  After Update ?

**Comment by ngdanghau** [comment]
On 10.13 — high sierra. And yes

**Comment by chris1111** [comment]
> On 10.13 — high sierra. And yes

try this version
[VoodooPS2Controller.kext.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator/files/3193465/VoodooPS2Controller.kext.zip)

**Comment by ngdanghau** [comment]
it don't work. So you can see error:
https://www.youtube.com/watch?v=L-GPLq8F2XE
I can't use touchpad and after try use it, i also can't use mouse????

**Comment by chris1111** [comment]
Maybe you need rebuild relink kernel after Update ?
Run this command
[Rebuild Prelink-kernel.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator/files/3193559/Rebuild.Prelink-kernel.zip)

**Comment by ngdanghau** [comment]
it remain so

**Comment by chris1111** [comment]
I don't know what's wrong here ?
