### ISSUE TITLE
Settings for High Sierra in Clover?

### ISSUE THREAD

**Issue by jbwharris** [chris1111/HP-Probook-EliteBook-Package-Creator#22]
I followed along with the video and created an installer for my 6460b, but I wasn't creating one for High Sierra and not Catalina. Is there somewhere I can get the proper Clover settings for High Sierra? Using the settings in the video resulted in an installation failed error in Clover. I'm using Sierra to create this media, though do have a Mojave build on another laptop if that helps.

**Comment by chris1111** [comment]
You do not give information about the failure of the installation and your subject is a bit confused

**Comment by jbwharris** [comment]
Ended up using another method to get the installer working.
