### ISSUE TITLE
install macos mojave 10.14.4 on my hp probook 4730s

### ISSUE THREAD

**Issue by huantransuper** [chris1111/HP-Probook-EliteBook-Package-Creator#23]
Can I install macos mojave 10.14.4 on my hp probook 4730s? I see your update no longer supports support for series 6 :(

**Comment by chris1111** [comment]
You can Install on other way but is not support by my program because the Intel HD 3000 patch was Remove from the program

**Comment by huantransuper** [comment]
@chris1111 What is wrong with the Intel HD 3000 patch?

**Comment by chris1111** [comment]
> @chris1111 What is wrong with the Intel HD 3000 patch?

Nothings wrong 
It's the spame about this patch that are wrong.
I have no time to answer the spames

**Comment by huantransuper** [comment]
Thank you very much!

**Comment by olakunle4luv** [comment]
I would appreciate if you can continue the update on HP series 6 laptop. I don't mind paying you for the work process. I really appreciate your hard work over this project. There are more of my customer requesting for this services on the HP series 6 Laptop. i am expecting your feedback on this. Thanks
