### ISSUE TITLE
Can't boot usb install macOS High Sierra on HP4830s

### ISSUE THREAD

**Issue by huantransuper** [chris1111/HP-Probook-EliteBook-Package-Creator#24]
![fb74b941a02e46701f3f](https://user-images.githubusercontent.com/41030688/66416119-5c058300-ea27-11e9-8b0a-af1b7c32b240.jpg)
Can't boot into USB. My computer's HP probook 4730s, I installed macos-10.13.6. But when booting into usb it only shows the black screen and the cursor as shown. Help me please.

**Comment by chris1111** [comment]
boot in verbose boot and try differant USB Port

**Comment by huantransuper** [comment]
![4c5ebaa648c9ae97f7d8](https://user-images.githubusercontent.com/41030688/66445699-d824b880-ea71-11e9-9298-427259da690c.jpg)
I use -v to get this bug

**Comment by chris1111** [comment]
make sure bios is setup good and try a diferant usb port

**Comment by chris1111** [comment]
What is the exact Specification of the laptop ?
Post here complet Specification

**Comment by huantransuper** [comment]
my laptop: 
HP Probook 4730s - Intel Core i5
Intel® Core™ i5-2520M CPU @ 2.50GHz × 2
Intel HD Graphics 3000 and AMD RadeonHD 7470M

**Comment by chris1111** [comment]
> my laptop:
> HP Probook 4730s - Intel Core i5
> Intel® Core™ i5-2520M CPU @ 2.50GHz × 2
> Intel HD Graphics 3000 and AMD RadeonHD 7470M

You have to **disable the AMD RadeonHD 7470M in the bios** because this car is not Usable with the Intel HD 3000

**Comment by huantransuper** [comment]
I looked at the bios setting, I thought there was no place to turn it off

**Comment by chris1111** [comment]
try under Graphics Injector on Clover Option
Setup like this image 

![scree122](https://user-images.githubusercontent.com/6248794/66503786-e258ae00-ea95-11e9-920a-565a81dc1456.png)


Type enter for Save
Return / return/ 
Boot verbose boot

**Comment by huantransuper** [comment]
![888780ad39c7df9986d6](https://user-images.githubusercontent.com/41030688/66505147-ed8ef680-eaf4-11e9-96ae-580698c2a536.jpg)
I tried it and it still got the error above

**Comment by chris1111** [comment]
Your FakeID not Setting good

You need this

**0x00010000**

**Comment by huantransuper** [comment]
I have successfully installed mac. But after installing the fan, the fan is very noisy. Do you have any suggestions for me?

**Comment by chris1111** [comment]
How did you proceed for make it bootable ? Because this is not supposed to happen, what macOS have you installed?

I can not really help you if you did other things than using the HP ProBook installer

**Comment by huantransuper** [comment]
I changed the FakeID as you said it to 0x00010000. I installed macos 10.13.6. I only use "HP ProBook installer" and do not use anything else. After installing, if you use too many tasks, it will be frozen.

**Comment by chris1111** [comment]
which fan patch have you selected

**Comment by huantransuper** [comment]
I choose fanSmooth. Currently I have to turn off the device to power down many times. Because it could be used for a while, it couldn't be helped

**Comment by chris1111** [comment]
I know, I understand but How did you boot macOS after post installation ? 
I hope you do not always use the FAKE ID
what exactly were all the choices you made with the program ?
Post here the EFI folder of the drive macOS , make EFI on ZIP file
thanks

**Comment by huantransuper** [comment]
Where can I find this folder? (EFI)

**Comment by chris1111** [comment]
> Where can I find this folder? (EFI)

Use Drop EFI on your application for mounting EFI partition

Please you have to answer my question

_I know, I understand but How did you boot macOS after post installation ?
I hope you do not always use the FAKE ID
what exactly were all the choices you made with the program ?_

**Comment by huantransuper** [comment]
I know, I understand but How did you boot macOS after post installation ?
I hope you do not always use the FAKE ID
what exactly were all the choices you made with the program ?
![b89db4d1c2a924f77db8](https://user-images.githubusercontent.com/41030688/66699303-e4c63c80-ed0f-11e9-808a-904b3597b78a.jpg)
![adc4aa86dcfe3aa063ef](https://user-images.githubusercontent.com/41030688/66699304-e5f76980-ed0f-11e9-877b-30ba43ddb982.jpg)
![58543c044a7cac22f56d](https://user-images.githubusercontent.com/41030688/66699305-e7289680-ed0f-11e9-8c57-bbd6bd1bf9b3.jpg)

**Comment by chris1111** [comment]
Post EFI Folder on ZIP 
[DROP EFI](https://youtu.be/140ZsBm9RrU)

**Comment by huantransuper** [comment]
Sorry for my delay. I did not choose "Atheros wifi AR9285". This is my EFI file/Users/ez_vl/Desktop/Archive.zip

**Comment by huantransuper** [comment]
.

**Comment by chris1111** [comment]
no EFI

**Comment by huantransuper** [comment]
https://drive.google.com/file/d/1KbAMcEI7HFKo9MWvZGtVoi0chVJSYofi/view?usp=sharing

**Comment by chris1111** [comment]
Try this DSDT.aml 
I change the fan patch and add Atheros patch for wifi
Replace on EFI/ACPI/patched

reboot laptop and see

**Comment by huantransuper** [comment]
My wifi could not find wifi. It is only looking for network

**Comment by chris1111** [comment]
Before I patching DSDT did you Connect to WIFI ?

**Comment by huantransuper** [comment]
Yes, before that I had a normal wifi connection

**Comment by huantransuper** [comment]
I rebooted again and it worked. But the system is very slow. Often jerky, frozen, unable to perform any action. At such times I usually have to turn off the device by the power button

**Comment by chris1111** [comment]
I have patch another DSDT for disable the Radeon HD 
DSDT attaching

Post system report of the About this mac i Will see
[DSDT.aml.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator/files/3720840/DSDT.aml.zip)

**Comment by huantransuper** [comment]
This is my report file. Thank you very much for the enthusiastic help
[MacBook Pro.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator/files/3720854/MacBook.Pro.zip)

**Comment by chris1111** [comment]
Ok looks good to your System report
The only thing is the Camera not recognise maybe you have a incompatible camera Device and its a rare thing for the Probook but is possible

**Comment by huantransuper** [comment]
But the system is very slow. It lagged, i will shutdown by the power button. By turning on 3 safari tabs only, it can crash

**Comment by chris1111** [comment]
make a video of the issue

**Comment by huantransuper** [comment]
It happens often
https://drive.google.com/file/d/11vSzwIvcFOXh-dTBMiCBcYxOdOLBaLbg/view?usp=sharing

**Comment by chris1111** [comment]
Ok I see this is relate to the Graphics I Think.  Intel HD 3000 and the Radeon HD 
Try to use the first DSDT without disabling Radeon and disable the radeon by SSDT

See this
http://www.attabot.org/mac-os/turn-off-discrete-amd-radeon-graphics-hackintosh-ssdt/

**Comment by huantransuper** [comment]
@chris1111 go to "Third Step - Compile SSDT". I can not find the SSDT which contains  \_SB.PCI0.PEG0.PEGP function.
Confirm that this function consists of _INI, _ON, _OFF, etc methods.
[123.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator/files/3721894/123.zip)
