### ISSUE TITLE
Two issues on Catalina and Mojave!

### ISSUE THREAD

**Issue by Mtkhan13** [chris1111/HP-Probook-EliteBook-Package-Creator#25]
Hi,

First of all thanks a lot for making this useful tool. I been using this for Mojave which worked awesome!

I have two issues to get help for you;
1st as you can see the attached image, its showing progress bar shifted and overlapped on right side instead of center. It was also the same on Mojave, how can I fix this?
2nd I'm using this updated tools for Catalina and its stuck at the same screen. I been waited for 20 minutes hoping it will progress but noting happened, no progress or error showed. I also tried to boot in verbose mode but all text was overlapped and shifted to right. I couldn't read it.

So please tell me how can I fix these issues? I'm using Elitebook 8470p with HD4000 graphics, 8GB RAM and SSD.

I will wait for your reply and thanks again for help.

Cheers!

![WhatsApp Image 2019-10-22 at 10 00 55 PM](https://user-images.githubusercontent.com/22547975/67312095-2cbc3f00-f51a-11e9-8011-8a398265e7b9.jpeg)

**Comment by chris1111** [comment]
For the image you need **UEFI Hybrid with CSM** in the bios setup
You can not Update for Catalina, you need a fresh Install with the Create Install media tools and booting from USB Create Install media, not footing from Mojave HD

**Comment by Mtkhan13** [comment]
Thanks for reply. 
I wasn't footing  😊 from Mojave HD, it was a fresh install. But I will definitely check the bios settings once again. 

Thanks !
-- 
Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 10/23/19, 1:27 AM chris1111 <notifications@github.com> wrote:
For the image you need UEFI Hybrid with CSM in the bios setup
You can not Update for Catalina, you need a fresh Install with the Create Install media tools and booting from USB Create Install media, not footing from Mojave HD

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator/issues/25?email_source=notifications\u0026email_token=AFMA4B4WWNM4D2OW2RMVR43QP5O4HA5CNFSM4JDSZXT2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEB7CT2I#issuecomment-545139177",
"url": "https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator/issues/25?email_source=notifications\u0026email_token=AFMA4B4WWNM4D2OW2RMVR43QP5O4HA5CNFSM4JDSZXT2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEB7CT2I#issuecomment-545139177",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Mtkhan13** [comment]
Hi Chris, 
I have changed the BIOS settings to UEFI Hybrid with CSM. 
But still the USB boot is stuck at this stage. Please tell me what's wrong and how to fix?
![WhatsApp Image 2019-10-24 at 12 24 29 AM](https://user-images.githubusercontent.com/22547975/67427668-f6ec8880-f5f5-11e9-8251-49060b0d4258.jpeg)

**Comment by chris1111** [comment]
Your not boot from USB Installer, thats evident!

**Comment by Mtkhan13** [comment]
Should I make the installer again? now I started again with USB but still stuck at this screen?

**Comment by chris1111** [comment]
> Should I make the installer again? now I started again with USB but still stuck at this screen?

No your not stras from USB installer , I see on verbose text 
Boot F9
Boot from EFI File
Boot from EFI ------- USB 
EFI/BOOT/BOOTX64.efi

**Comment by Mtkhan13** [comment]
okay let me try F9

**Comment by Mtkhan13** [comment]
It worked!
Thank you again!

Once it copies the file on SSD will I need to boot from F9 again? I believe my old EFI Folder in on SSD. Though I have deleted the APCI Folders files in SSD.

![WhatsApp Image 2019-10-24 at 1 03 01 AM](https://user-images.githubusercontent.com/22547975/67429915-94e25200-f5fa-11e9-9d7a-a3a97f5aa47a.jpeg)

**Comment by chris1111** [comment]
Backup your EFI if you need it but you need to erase the drive on disk Utility and for post Install using the HP ProBook EliteBook macOS
Latest package

**Comment by Mtkhan13** [comment]
Sure, I will do that.

**Comment by Mtkhan13** [comment]
Hi Friend, one request if you can allow me to reach you through email? my email is mtkhan@email.com sorry for contacting here.

**Comment by chris1111** [comment]
> Hi Friend, one request if you can allow me to reach you through email? my email is [mtkhan@email.com](mailto:mtkhan@email.com) sorry for contacting here.


Sure My Email is leblond1111@gmail.com
