### ISSUE TITLE
Elitebook 8570p booting into Black Screen

### ISSUE THREAD

**Issue by Mtkhan13** [chris1111/HP-Probook-EliteBook-Package-Creator#26]
Hi Chris,
Earlier post issues were resolved awesomely.

I'm converting my 2nd laptop 8570p now and I have double checked the bios settings and other things. All are good, USB installer shows no error in verbose mode and boots into the OS installer screen but it shows only a black screen, no display at all. I also checked with Mojave USB which I created with earlier version of your app. It show same issue with that too.

Please tell me what how can I fix this? 

Laptop specs are Elitebook 8570p 8GB RAM, HD-4000 GPU, SSD and Atheros AR5B195 Wifi. 

Waiting for your reply!
Thanks

**Comment by chris1111** [comment]
Try to change USB port and make sure fast boot is disable and booting verbose boot

**Comment by Mtkhan13** [comment]
Okay let me try.

**Comment by Mtkhan13** [comment]
Fast boot is disabled and booted in verbose mode, no issues shown in log. I changed the USB port but got into the showing same black screen.

**Comment by chris1111** [comment]
Do you have 1600x900 resolution? if yes try Injectintel =false

**Comment by Mtkhan13** [comment]
Yes it has 1600x900 resolution. Let me try this.

**Comment by Mtkhan13** [comment]
Thank you very much, it really worked!

**Comment by chris1111** [comment]
Thanks to you!  I add you in the testers on the main page and in the readme of the program
![Capture d’écran, le 2019-10-26 à 18 23 04](https://user-images.githubusercontent.com/6248794/67626791-9ab87d00-f81e-11e9-82db-280208a22001.png)
🛠😀

**Comment by Mtkhan13** [comment]
Thank you Chris, honored to be a part of it. 
Thanks a lot!
-- 
Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 10/27/19, 3:31 AM chris1111 <notifications@github.com> wrote:
Thanks to you!  I add you in the testers on the main page and in the readme of the program



🛠😀



—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator/issues/26?email_source=notifications\u0026email_token=AFMA4B5TWDVJZA4IJCABNDLQQTALPA5CNFSM4JFOITBKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECKSH4Y#issuecomment-546644979",

"url": "https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator/issues/26?email_source=notifications\u0026email_token=AFMA4B5TWDVJZA4IJCABNDLQQTALPA5CNFSM4JFOITBKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECKSH4Y#issuecomment-546644979",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by Mtkhan13** [comment]
Chris, do you also build app for HP tower workstations? I have z400 and z800 and I also have my own method of making them work with mac. 

I can share that with you so you can make a better app for that too. I been using Enoch and vanilla method but clover seems not working option yet for me so far. 
-- 
Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 10/27/19, 3:31 AM chris1111 <notifications@github.com> wrote:
Thanks to you!  I add you in the testers on the main page and in the readme of the program



🛠😀



—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator/issues/26?email_source=notifications\u0026email_token=AFMA4B5TWDVJZA4IJCABNDLQQTALPA5CNFSM4JFOITBKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECKSH4Y#issuecomment-546644979",

"url": "https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator/issues/26?email_source=notifications\u0026email_token=AFMA4B5TWDVJZA4IJCABNDLQQTALPA5CNFSM4JFOITBKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECKSH4Y#issuecomment-546644979",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
