### ISSUE TITLE
How can I dual boot with windows 10? Is it possible?

### ISSUE THREAD

**Issue by Mtkhan13** [chris1111/HP-Probook-EliteBook-Package-Creator#27]
Hi Chirs,
Thanks for the previous help and support and adding me in your testers list.!

I wanted to know if we can also dual boot windows and mac together using your tool? I have separate drives for Windows and mac but it's not booting after I install mac on it? Will it be possible?

HP Elitebook 8570p, HD4000, SSD [Mac] and HDD [Windows] 8GB Ram.

I will wait for your reply.
Cheers!

**Comment by chris1111** [comment]
If windows is UEFI  thats boot no problem
