### ISSUE TITLE
Hello Chris , installing catalina on 4530s with package

### ISSUE THREAD

**Issue by kenimalo** [chris1111/HP-Probook-EliteBook-Package-Creator#31]
hello , I wonder if I can install with you package  Catalina on 4530s. at the moment I have Catalina working but anyways looks interesting retrying solving some issues. 
Two issues.
1....I know that I have f60 bios (not f50 as you say for 6 series) .
2... selecting in post install 6 or 7 series seem to be connected with version of OS, >>what are the options?
thank you in advance

**Comment by chris1111** [comment]
Sorry but this is not an issue
