### ISSUE TITLE
Memory Panic Issue after Post Install 

### ISSUE THREAD

**Issue by roto31** [chris1111/HP-Probook-EliteBook-Package-Creator#33]
I was able to install Catalina using this method to create a USB drive. The issue I am now running into now after the post install, is when running in verbose mode it stops after the first stage of starting up and ends with "** In Memory Panic Stackshot Succeeded ** Bytes Traced 10800 ** Attempting system restart MACH Reboot 

The above is not an error message I have not saw before. Thoughts?

_Originally posted by @roto31 in https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator/issues/32#issuecomment-609524008_

**Comment by chris1111** [comment]
Tell us to dosdude1 your not using the guide here so issue was delete
