### ISSUE TITLE
Error at time creates EFI

### ISSUE THREAD

**Issue by Macauty** [chris1111/HP-Probook-EliteBook-Package-Creator#35]
Hi, I do all steps, step by step carefully but at tiem I am generating EFI, after I select kexts and system says "6 min remain" it finish quickly with an error while instalation, contact with software admin to ask for help.

I attached log file generated in usb-EXT-HD formating in GUID partition map. Content in this log file is:

Clover EFI installer log - Mon Apr  6 20:46:47 CEST 2020
Installer version: v2.5k r5103 EFI bootloader
======================================================
/dev/disk0 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *250.1 GB   disk0
   1:                        EFI EFI                     209.7 MB   disk0s1
   2:                  Apple_HFS SSD                     124.9 GB   disk0s2
   3:                 Apple_Boot Recovery HD             650.0 MB   disk0s3
   4:                 Apple_APFS Container disk1         124.3 GB   disk0s4

/dev/disk1 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +124.3 GB   disk1
                                 Physical Store disk0s4
   1:                APFS Volume APFS HD                 8.3 GB     disk1s1
   2:                APFS Volume Preboot                 43.1 MB    disk1s2
   3:                APFS Volume Recovery                20.5 KB    disk1s3

/dev/disk2 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *32.2 GB    disk2
   1:                        EFI EFI                     209.7 MB   disk2s1
   2:                  Apple_HFS Install macOS Catalina  31.9 GB    disk2s2

/System/Library/Extensions/msdosfs.kext failed to load - (libkern/kext) operation/kext not allowed at current boot level; check the system/kernel logs for errors or try kextutil(8).
mount_msdos: msdos filesystem is not available

ERROR: can't mount ESP partition (disk2s1) !
Check that the partition is well formated in HFS or Fat32.

To format as HFS use command like:
sudo newfs_hfs -v EFI /dev/rdisk2s1

For format as Fat32 use command like:
sudo newfs_msdos -v EFI -F 32 /dev/rdisk2s1
[Clover_Install_Log.txt](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator/files/4440315/Clover_Install_Log.txt)

Could you help me please??
Thanks in adavande, regards and sorry about my english!!

**Comment by Macauty** [comment]
Sorry about my english. What I mean is that I have got an error in the step which is in minute 13:27 on your youtube video-guide  (https://www.youtube.com/watch?v=0M10TUtsnGA&feature=youtu.be)
And that is the log which this step generates on usb-EXT-HD... any idea? I have got the USB pendrive in the correct format and I have done this step many times...

**Comment by chris1111** [comment]
What is the macOS version you have to create the USB ? It is a real Mac or Hackintosh, It is a  Virtual Machine ?

**Comment by Macauty** [comment]
It is a Hackintosh Mojave 10.14.1

**Comment by Macauty** [comment]
Hi again. Forget this, I have fixed it creating 'EFI' partition in my usb pendrive in other PC with TransMac. After, I have delete the files generates with TransMac in this 'EFI' partition and I have done your process succssesly, selecting like install location (minute 10:28 in your video-guide) the 'EFI' TransMac partiton generated before instead of 'Install macOS Catalina'. I have copy the installation package and your files like in your video-guide in 'EFI' partition and in 'Install macOS Catalina' partition... 
But when i go to install Catalina, I boot from EFI file and start to process a lot of code lines and stop and freezze in this line: 

IOConsolerUsers: gIOScreenLockState 3, hs 0, bs 0, now 0, sem 0x0

After some minutes screen get turn off an if I press some key, keboard get turn on light but not screen... Absolutly freezze... I have to turn off the laptop with button...

This same  with these code line, I have suffered with other guides, so now I think is it not about your guide... I thought that your guide was going to be different and I would get it, but.... some idea please?

**Comment by chris1111** [comment]
What is the HP Laptop and complet hardware of the laptop ?

**Comment by Macauty** [comment]
It is a HP EliteBook folio 9470m
i7, 12GB RAM, Intel HD 4000, WiFi Intel (I know this is not going to works)

**Comment by chris1111** [comment]
> It is a HP EliteBook folio 9470m
> i7, 12GB RAM, Intel HD 4000, WiFi Intel (I know this is not going to works)

Looks like you have a 1600x900 screen so boot Inject intel false to install macOS

**Comment by Macauty** [comment]
Ok, could you tell me how please??

**Comment by chris1111** [comment]
Clover / Option /Graphics Injector /Inject Intel 
uncheck the box by Enter then return to the menue booting to macOS

**Comment by Macauty** [comment]
Ok thank you so much for your support. I will try it tomorrow. My girlfriend are going to kill me!! I will let you know...

**Comment by Macauty** [comment]
Hi again. Well, I have some news. At first, I did the 'Inject Intel', but in 'Clover / Option /Graphics Injector /Inject Intel', the chec box was uncheck!! To do something, I dissabled it and surprise, it did work fine! I installed Catalina without more problems... Cool!!!!

But this is not a easy path... I tell from my own sweat... I did your steps in video-guide (minutes from 17:20 to 24:31). When I restarted I had a kernel panic error.... oooooohhhhhhhhh!!!!! Now, in new HP Clover I have two options (in both, I have kernel panic error, but with diferent line-codes before). I am going to try attach two pictures from this:
![picture a](https://user-images.githubusercontent.com/63187749/78676721-1c8cf600-78e7-11ea-9727-de4cca218a48.jpg)
![picture b](https://user-images.githubusercontent.com/63187749/78676725-1e56b980-78e7-11ea-8291-2b1d4f88d79d.jpg)

- Boot Recovery from Recovery (picture A)
- Boot macOS from SSD (picture B)

Please, could you help me?

**Comment by chris1111** [comment]
what is the bios version you have ?

**Comment by Macauty** [comment]
98IBD Ver. F.66

**Comment by chris1111** [comment]
You have only one Graphics Intel HD 4000, no Radeon or Geforce ?

**Comment by Macauty** [comment]
Yes, I think so. I have looking for something about in BIOS and I can find nothing... And when I had W10, in device manger I only had Intel HD 4000.

**Comment by chris1111** [comment]
This is strange ? try booting inject intel=false

**Comment by Macauty** [comment]
Yes, I tried... for test something... and it doesn't work... It is hard... but I dont want to abort this project... any idea please?

**Comment by chris1111** [comment]
retry new installation its suppose to work, its already made by someone in the past

**Comment by Macauty** [comment]
Ok... I will try tomorrow... I'll notice to you... thanks so much!!

**Comment by Macauty** [comment]
Hi, I have been today all day trying this and I have not be able to success it... but I have notice something about permission, you will see.

I can install Catalina from usb pendrive with 2 partitions. One of them for EFI partition, and the other one for Catalina OS. So I can install withou problems (today at least 6 times!!) 

But when OS run, I have not LAN, no battery, no sleep, have not audio and have not WiFi (but WiFI I know that I will not have because is original from this laptop (9470m)... So I launch yor app with the same settings that in your video-guide less the laptop model that I choose 9x70 (in one of the test I selected the same like you to test and nothing, the same) and proccess end ok the first time. If I launch the software for a second or third time end with an error saying contact whith the owner software...  Ok, I launch software with item choosed and end ok. I reboot and kernel panic, like yesterday...

But I have noticed that when software end ok, I go to Macintosh HD drive (formated in APFS GUID) and it has not EFI-Backup folder!! So I try create a new folder in this drive and I can not do it... EFI partition is created ok

If I go to see permissions Hacintosh HD drive, I see 'system' has read and write' but admin has only read permissions (attached picture). I try to change it but nothing happens... obiusly I click over padlock and write my password, but when I try to cahnge from 'read' to 'read an write' nothing, back to 'read'... is it normal? Or maybe my problems can be here?

Thanks so much! I wish you have a light and you can help me...

**Comment by Macauty** [comment]
Sorry, forget attach the picture. Here is...
![20200408_224428](https://user-images.githubusercontent.com/63187749/78835822-2ac73900-79f1-11ea-9284-8515cd62f5ca.jpg)

**Comment by chris1111** [comment]
Follow the guide correctly for making perfect post install
