### ISSUE TITLE
DRM Green screen issue 

### ISSUE THREAD

**Issue by roto31** [chris1111/HP-Probook-EliteBook-Package-Creator#36]
So far everything works quite well on the HP 8470p. No major issues, and everything works in the way an OEM MacBook Pro would. The only issue that popped up that is not a major issue but annoying when your kid wants to watch Disney Junior is the green screen DRM issue. We get perfect sound and there is a green screen but we can see what is supposed to be there when scrobbling through the video. 

What is the issue that causes this and how can it be resolved? 

I have an HP 8460p which I installed Catalina on and then applied your legacy GPU patcher to patch the Intel 3000 graphics. This one does not have the DRM green screen issue.

**Comment by chris1111** [comment]
Video AppleTV is known issue
