### ISSUE TITLE
Can't boot usb install maOS Mojave on HP8460p

### ISSUE THREAD

**Issue by ngdanghau** [chris1111/HP-Probook-EliteBook-Package-Creator#4]
Hi, I create usb installer from this Creator but when I boot from usb, it show error icon  instead
of apple icon.

**Comment by ngdanghau** [comment]
![mac-prohibit-symbol-screen-icon](https://user-images.githubusercontent.com/33993567/47966110-85da4c80-e003-11e8-8871-56ccd109b555.png)

**Comment by chris1111** [comment]
Which macOS you try ?
Thats not error its boot failed
Boot in verbose mode ( -v)  post picture if the boot stop

**Comment by ngdanghau** [comment]
I install macos 10.14

**Comment by ngdanghau** [comment]
![img_0008](https://user-images.githubusercontent.com/33993567/47966593-1ff0c380-e009-11e8-89a1-717c8fbe0745.JPG)

**Comment by ngdanghau** [comment]
Thanks very much. It work
