### ISSUE TITLE
Issues with 6 Series HP 8460p Laptops

### ISSUE THREAD

**Issue by kordak-mm** [chris1111/HP-Probook-EliteBook-Package-Creator#40]
I have been completely successful in installing Mojave and Catalina on my Elitebook 8470p with everything working.  Best tool that I have used in the past 10 years of Hackintoshing, thank you for your time and work.

I have two HP Elitebook 8460p which I have successfully installed Sierra in the past.  I wanted to create new installs of Sierra and High Sierra on these machines. However, when I use the package creator on these machines I can only get the two right side USB parts to work.  I have tried to install Sierra or High Sierra several times but only two ports working.  I tried USBInjectAll.kext but even this does not activate the left 2 USB ports.   The ports are not broken.  Any suggestions?

**Comment by chris1111** [comment]
Thanks
Have a look here
https://github.com/chris1111/USB-3.0-NEC
chris 1111
leblond1111@gmail.com

**Comment by kordak-mm** [comment]
chris 1111, 

  The USB-3.0-NEC package worked splendidly!  Now both Elitebook 8460p models I am working with have all USB ports functioning.

  Many thanks again for your packages, great informational videos, and your other valuable contributions to better understanding.  Many thanks again!
