### ISSUE TITLE
About fingerprint reader and AMD graphics card...

### ISSUE THREAD

**Issue by ThangMarvel** [chris1111/HP-Probook-EliteBook-Package-Creator#41]
+ How to enable fingerprint for: HP Elitebook 8570P i5 3210M Intel HD 4000 (Camera Facetime ok?)

+ And for now, there are WhateverGreen + LiLu, can I install Catalina into HP Probook 4730S I5 2520M AMD Radeon HD 7470M/6490M

(Are you planning to integrate above stuffs into HP-Probook-EliteBook-Package-Creator or users have to do workarounds by themself, please?)

**Comment by chris1111** [comment]
Np plan for Radeon HD
