### ISSUE TITLE
DW1520 in X240

### ISSUE THREAD

**Issue by Silfalion** [chris1111/HP-Probook-EliteBook-Package-Creator#43]
got a dw1520 card taken off an HP probook. Would it work on a Lenovo Thinkpad x240? like is there a bios requirement or something?

**Comment by chris1111** [comment]
No This is the WIFI model for Thinkpad x240

![Capture d’écran, le 2020-08-16 à 16 35 08](https://user-images.githubusercontent.com/6248794/90343486-b758b800-dfde-11ea-88b7-f98d7aff42aa.png)
