### ISSUE TITLE
Reboot to 75% HP Elitebook 2560p

### ISSUE THREAD

**Issue by jtrigon** [chris1111/HP-Probook-EliteBook-Package-Creator#45]
Primero en felicitarte por este proyecto. Lo conocí hace una semana y me dio un cumplido.
Mi consulta es la siguiente: Estoy tratando de instalar Sierra alta en mi portátil hp elitebook 2560p. No pude empezar, pero arreglarlo modificando el inyección de Intel. Ahora el problema es que cuando está en 75% El sistema recae y luego se inicia de nuevo desde el sistema hd y me dice una instalación incorrecta. ¿Sabes cuál puede ser el problema?

**Comment by chris1111** [comment]
Use google translate

**Comment by jtrigon** [comment]
Sorry, I put the original version not the translated one.
First to congratulate you on this project. I met him a week ago, I was surprised and I consider a magnificent job done.
My query is as follows: I am trying to install High Sierra on my hp elitebook 2560p laptop. I couldn't get started, but fix it by modifying the Intel injection. Now the problem is that when it is at 75% or so, the system reboots and then boots again from the hd system and tells me an incorrect installation. Do you know what the problem can be?

**Comment by chris1111** [comment]
maybe a corrupt app
