### ISSUE TITLE
MACH Reboot Error on HP 2170p

### ISSUE THREAD

**Issue by ieseberri** [chris1111/HP-Probook-EliteBook-Package-Creator#46]
Hello, 

I’ve followed your guide to install Catalina in one Elitebook 2170p without success. After the first reboot it stops with the MACH Reboot message. 

How can I solve the problem? Thank you!

**Comment by chris1111** [comment]
You nee wait 4 at 5 time reboot for Big Sur 
Big Sur = WAIT!

**Comment by ieseberri** [comment]
Hello Chris,

I want to install Catalina not Big Sur.

**Comment by chris1111** [comment]
> Hello Chris,
> 
> I want to install Catalina not Big Sur.
> 
> I've followed your steps, and after boot from second time (when it finishes the installation and then estimates the time for booting) the system reboots and after booting again appears the MACH Reboot Error messsage.
> 
> Any guidance?
> 
> Thank you for your time.

Some times you have to boot 2 or 3 time after seeing estimate time

**Comment by ieseberri** [comment]
Hello Chris,

I've installed in my computer HP Elitebook 2170p F68. I runs well, the only trouble I've got now is with the WIFI card. I've got an Azure AW-CE-123H and it seems does not work OOB.

Anyway, thank you for your help!

**Comment by chris1111** [comment]
> Azure AW-CE-123H

Dont use AirportBrcmFixup.kext
use [FakePCIID and FakePCIID_Broadcom_Wifi.](https://bitbucket.org/RehabMan/os-x-fake-pci-id/downloads/)

**Comment by ieseberri** [comment]
Hello Chris,

I have to admit I’m fairly new to OC. How can I install the kexts? Do I have to copy them to the EFI folder or I have to copy then to S/L/E? 

And after copy the files which are the next steps? 

Thank you. 

Iñaki Eseberri

**Comment by chris1111** [comment]
this program here not use Opencore
