### ISSUE TITLE
brightness key did not work on prebook 4540s

### ISSUE THREAD

**Issue by ostadnart** [chris1111/HP-Probook-EliteBook-Package-Creator#47]
I installed Mojave on my 4540s by your guide, every thing work, only brightness key did not work.
after install clover I did not have sound that by installing voodoo kext it be solved but brightness problem no.

**Comment by chris1111** [comment]
If you use vodoohda you need remove AppleALC.kext
Send me here on ZIP the EFI please

**Comment by ostadnart** [comment]
refi folder as zip is about 50mb that GitHub don't allow to upload
I have dual boot

**Comment by chris1111** [comment]
> refi folder as zip is about 50mb that GitHub don't allow to upload
> I have dual boot

Link external

**Comment by ostadnart** [comment]
> > refi folder as zip is about 50mb that GitHub don't allow to upload
> > I have dual boot
> 
> Link external

I will upload it to mega and she link

**Comment by ostadnart** [comment]
> If you use vodoohda you need remove AppleALC.kext
> Send me here on ZIP the EFI please

how removeAppleALC.kext?

**Comment by ostadnart** [comment]
> > refi folder as zip is about 50mb that GitHub don't allow to upload
> > I have dual boot
> 
> Link external
https://mega.nz/file/c15mjJ6J#AU6cCfuJTG1QMoiSidYB07tKHOi-73tsmCoou3HF064

**Comment by chris1111** [comment]
> > If you use vodoohda you need remove AppleALC.kext
> > Send me here on ZIP the EFI please
> 
> how removeAppleALC.kext?


EFI/CLOVER/kexts/10.12/AppleALC.kext

**Comment by chris1111** [comment]
I see you have lots of diferant kext in EFI/CLOVER/kexts/Other
Its suppose to be only FakeSMC and the plugin for my guide, so you have modifying some thing as you wanted
![Capture d’écran, le 2020-10-10 à 08 14 57](https://user-images.githubusercontent.com/6248794/95654830-b9b42b80-0ad0-11eb-811d-b0c04f1da1a7.png)

So try to change the DSDT in /EFI/CLOVER/ACPI/patched and you have to remove AppleALC.kext, AppleBacklightInjector.kext from /EFI / CLOVER / kexts / Other
[DSDT.aml.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator/files/5358952/DSDT.aml.zip)


if it does not work I cannot help you because the guide is not followed

**Comment by ostadnart** [comment]
thanx

**Comment by ostadnart** [comment]
by removing that, brightness key back and work.

**Comment by ostadnart** [comment]
thanx for your greate Guide

**Comment by ostadnart** [comment]
and a question:
can I update from Mojave to Catalina and...directly?
need to reinstall clover?

**Comment by chris1111** [comment]
> and a question:
> can I update from Mojave to Catalina and...directly?
> need to reinstall clover?

no need update Clover

**Comment by ostadnart** [comment]
> > and a question:
> > can I update from Mojave to Catalina and...directly?
> > need to reinstall clover?
> 
> no need update Clover

thanx so much

**Comment by ostadnart** [comment]
excuse me
another problem:
after sleep,mojave can't wake up.
do you recommend this command?  

sudo pmset -a hibernatemode 0
sudo rm /var/vm/sleepimage
sudo mkdir /var/vm/sleepimage

**Comment by ostadnart** [comment]
> > and a question:
> > can I update from Mojave to Catalina and...directly?
> > need to reinstall clover?
> 
> no need update Clover

hello bro
sleep problem still not solved
after sleep screen goes black and I have to restart prebook

**Comment by ostadnart** [comment]
> no need update Clover
hello bro
sleep problem still not solved
after sleep screen goes black and I have to restart prebook
