### ISSUE TITLE
probbok 4540s can not wake up from sleep

### ISSUE THREAD

**Issue by ostadnart** [chris1111/HP-Probook-EliteBook-Package-Creator#48]
hi bro
probook 4540s can't wake up from sleep and remain on black screen.
I us sudo command to disable hibernate and wake up work but mouse cursor disappear.
I don't know where I have mistake in installation.
as per you said my kext folder seems different by your guide but I did nit do anything.i followed your guide.

Mojave start up in 55s.
every thing now work, only wake up from sleep.didn't

**Comment by chris1111** [comment]
https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator/issues/47

**Comment by ostadnart** [comment]
> #47 (comment)

I do it again and frame by frame follow youtube guide.i attach refi file now.
after restart no sound, no function key.i select from your prebook package correct items for 4540s as 7series.
brightness not work, sound not work

**Comment by ostadnart** [comment]
https://mega.nz/file/N4hyESiL#n0Vgvb0QE8cNdP6RJOmtbDFbHmZDlIJAASxpBrtbxAc
