### ISSUE TITLE
Finder is not showing files until I switch the tabs couple of times

### ISSUE THREAD

**Issue by Mtkhan13** [chris1111/HP-Probook-EliteBook-Package-Creator#50]
Hello my friend, how are you doing? I've installed Mojave on Elitebook 8460p using this build but the Finder is not showing files until I switch the tabs couple of times. Can you please guide what is the issue and how to fix?

**Comment by chris1111** [comment]
strange ? I never see this

**Comment by Mtkhan13** [comment]
No problem, I found the solution by rebuilding the kernel cache using kext wizard. --Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 11/27/20, 3:24 AM chris1111 <notifications@github.com> wrote:

   
  strange ? I never see this
