### ISSUE TITLE
Legacy-Video-patch issue

### ISSUE THREAD

**Issue by budgierless** [chris1111/HP-Probook-EliteBook-Package-Creator#53]
hello, my 6560b the is not working correctly, it is install but the when testing using "VDADecoderChecker" i get this error..

% /Users/budgierless/Downloads/VDADecoderChecker ; exit;
VDADecoderCreate failed. err: -12473
An error was returned by the decoder layer. This may happen for example because of bitstream/data errors during a decode operation. This error may also be returned from VDADecoderCreate when hardware decoder resources are available on the system but currently in use by another process.
VDADecoderCreate failed. err: -12473

**Comment by budgierless** [comment]
also the DOCK on the desktop still dose no animation.

**Comment by chris1111** [comment]
6560b not support here why open issue
