### ISSUE TITLE
Should i update to Bigsur?

### ISSUE THREAD

**Issue by gzbenson** [chris1111/HP-Probook-EliteBook-Package-Creator#56]
My Spec
9470m , i7-3667U , 8G , 250g ssd , 94352hmb ,1600*900

Will this spec. run smoothly in BigSur?

**Comment by chris1111** [comment]
If you use this project,  update is not possible because you are using old Clover 
take look [here new program for Big Sur ](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC)
