### ISSUE TITLE
Some issues for High Sierra on HP ProBook 6460b

### ISSUE THREAD

**Issue by nello16** [chris1111/HP-Probook-EliteBook-Package-Creator#57]
Hi Chris,
first of all I want to give a big thanks for the great job you have done. After turning around the web looking for a good installation procedure I've found your Package Creator and everything as gone like a charm!!
I've only three issues and, before trying other solution with highly headache (with no success), I would ask if you can help me.
The three issue are:

- WiFi does not work: there is the empty symbol on the top bar but if I click to activate WiFi nothing happens
- Bluetooth does not appear in the SystemPreferences and doesn't work
- SD card reader does not work: if I insert an SD card nothing happens (else in the Disk Utility)

The laptop has an i3-2310m, 4GB RAM and a 250GB SSD
Attached you can find the zip of my EFI folder (btw, the Drop EFI app does not work, I mount it manually), and system info about the wifi card. The bluetooth is not recognized by the osx

Many thanks
nello

https://drive.google.com/file/d/11fD41TS18_0DsfkIRnn3V3wwyjMXpVJg/view?usp=sharing

![wifi](https://user-images.githubusercontent.com/78387883/106530095-f8d91300-64eb-11eb-9e30-ad86af269277.png)

**Comment by chris1111** [comment]
See video correctly Drop EFI works good
Bluethoot works if you have Internal bluethoot activate but the kext is probably to recent for High Sierra, same for the kext Wifi. this program is updated for Catalina and Mojave

**Comment by nello16** [comment]
Hi chris1111,
many thanks for the quickly answer! Sorry, I've forgotten what I've seen in the last part of the video...
Yes I've an internal bluetooth, but I think that my laptop is not able to run Mojave or Catalina.
So I've to find the right kext...The kext that I've to replace in the CLOVER/kext/10.13 folder are AirportBrcmFixup.kext, BrcmBluetoothInjector.kext, BrcmFirmwareData.kext and BrcmPatchRAM2.kext, right? Can you suggest a way to identify if they are good for HiSierra?
thanks
n

**Comment by chris1111** [comment]
Yea right 
Google AirportBrcmFixup.kext, for High Sierra
same for BrcmBluetoothInjector.kext, BrcmFirmwareData.kext and BrcmPatchRAM2.kext for High Sierra

**Comment by chris1111** [comment]
Try this
[Archive.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator/files/5907706/Archive.zip)

**Comment by nello16** [comment]
Sorry but it doesn't work. after reboot if I click on the wifi icon nothing happens, and the bluetooth does not appear in the system preference. What I can try?

**Comment by chris1111** [comment]
is this latest High Sierra Update?

**Comment by nello16** [comment]
10.13.6 version (17G66), security update 2020-05 not yet installed

**Comment by chris1111** [comment]
You have to find the right kext
[Old release](https://github.com/acidanthera/airportbrcmfixup/releases)
[Rehabman release](https://bitbucket.org/RehabMan/os-x-brcmpatchram/downloads/)

**Comment by nello16** [comment]
ok, many thanks, I will try and let you know

**Comment by chris1111** [comment]
You can try latest macOS Catalina, if you need **HOW to do it** let me known

**Comment by nello16** [comment]
Amazing, it would be great!!
I'm trying to load various kext versions but anyone works, almost for the wifi. I'm thinking that lilu.kext version is not good.
If you can guide me through Catalina it would be my pleasure!!
Wait to hear from you!!

**Comment by chris1111** [comment]
Do it new install of Catalina 10.15.7 make Update and do not install Post Install , just tell me me the you are complet Update and you are up to date

**Comment by nello16** [comment]
Just to verify if I have understand:
-download from AppStore Catalina 10.15.7 Installation App
-use you guide to create an install media USB
-install the OS X to the laptop
-let you know (I do not install the ProBook pkg)

I want to note you that the laptop is a ProBook 6460b with an i3-2610M, 4GB RAM and 250GB SSD, is it compatible?

Thanks

**Comment by nello16** [comment]
I add: the wifi card is an original BCM943244-HMS and the bt one is BCM92070M-DREF, no UBS 3.0 port

**Comment by chris1111** [comment]
yes correct after  install 10.15.7 you have another update, complete then let me know when you finish
Of course your Graphics not work but I will fix

**Comment by nello16** [comment]
ok, I will download Catalina this night and tomorrow I will build the installer an make the installation.
Thanks, I will update you

**Comment by nello16** [comment]
Hi Chris,
sorry but last days I was a little busy. I've installed Catalina and last update, now  Probook has 10.15.7 (19H114). The installation was not easy because the Setup Assistant crash after the question about the internet connection and the only way to go ahead was setting the flag "This computer does not connect to internet". So the issues that I've noted are:
-no ethernet card (maybe for the above setup)
-no whifi
-display only 1204x768 with no regulation
-no trackpad (it works only for scrolling page)
-no audio
-no card reader
-no bluetoooth
-no battery control
The only way to boot is using Clover on the usb key and choosing the Catalina probook disk.
Please let me know what are the next steps, I'm very curious :)
Thanks

**Comment by chris1111** [comment]
Ok install the Post Install the same choices you would have made in macOS High Sierra 
Dont reboot then use this
https://github.com/chris1111/Legacy-Video-patch
Good luck

**Comment by nello16** [comment]
Hi Chris,
great!! Everything has gone quite well. The remain issues are:
-wifi (when I click the top icon to activate the wifi it becomes with gray stripes for few seconds then return empty)
-bluetooth
-card reader
The most important is the wifi, do you have some workaround?
As I can see everything is in the right place.
thanks

**Comment by chris1111** [comment]
Send me EFI folder on zip here

**Comment by nello16** [comment]
the zip is more than 10MB, so I will send partial zip
[EFI1.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator/files/5938090/EFI1.zip)
[EFI2.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator/files/5938092/EFI2.zip)
[drivers.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator/files/5938094/drivers.zip)
[kext1.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator/files/5938095/kext1.zip)
[kext2.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator/files/5938097/kext2.zip)
![about-this-Mac](https://user-images.githubusercontent.com/78387883/107134208-48567f00-68f0-11eb-9a0f-15a222c9fbf4.png)

**Comment by nello16** [comment]
Could be the MacBook type in the config.list? This ProBook is more like a MacBook Pro 8,1

**Comment by chris1111** [comment]
what is the WIFI card exactly ?
Bluethhot is Internal ?

Card Reader Realtek or JMicron?

**Comment by nello16** [comment]
wifi is a BCM43244HMS
bluetooth is BCM9270M, internal
card reader I don't know but I suppose it's a JMicron

**Comment by chris1111** [comment]
I can't find any info about this wifi card in macOS 
Bluethoot is suppose to be working ? also card Reader if its JMicron 
this is weird

**Comment by nello16** [comment]
sorry, the wifi card I BCM943244HMS
![20210207_032359](https://user-images.githubusercontent.com/78387883/107134731-0ed44280-68f5-11eb-9122-6439274ccb94.jpg)

**Comment by nello16** [comment]
here is the bluetooth
![20210207_032500](https://user-images.githubusercontent.com/78387883/107134748-2dd2d480-68f5-11eb-83c7-dfb7e4143bd9.jpg)

**Comment by nello16** [comment]
The bluetooth icon isn't in the System Preferences, if I launch the the BT utility the message is that there isn't any Bluetooth hardware.

**Comment by chris1111** [comment]
Suppose to work WIFI I have the same card
make sur BIOS---  Device Option ---  LAN/WLAN Switching disable

**Comment by nello16** [comment]
![20210207_034616](https://user-images.githubusercontent.com/78387883/107143290-9f7e4300-6934-11eb-8853-c47ec4a7119b.jpg)
Hi Chris, 
sorry but yesterday was too late for me (I'm in Italy, it was 3.30am)
The option is disable, here there are the other settings
The card reader works if I insert di SDcard before the boot, after the boot, inserting the SD nothing happens

**Comment by chris1111** [comment]
No probleme Iam in North America in montreal Canada 😀 my Wife is I talienne
this is verry strange its probably a bad wifi card?
Fast Boot is also disable?
You can try to shutdown the laptop, unplug the battery and the power wire, push the power button for 30 seconds and restart the laptop.
you can also  try to push the network button on the top of the laptop?

**Comment by nello16** [comment]
Oh very beautiful Montreal! I was there during my marriage journey, I had visited all the French Region of Canada, very beautiful!! ...but it was about twenty years ago...
...came to Catalina... during my travel to make HiSierra working there was a time where the wifi and the card reader works for a while, I don't know why or how. Other things (display, trackpad, bt..) didn't work and loading kext o modifing .plist at next reboot wifi and card reader didn't work any more. The wifi card works in win7, win10 and linux.
I will check the FastBoot but I am quite sure it is disabled, and I will try the procedure you have written.
the push button on the top don't change color if I push it, it remains orange. during the initial phase of boot it is white then, before clover, change in orange.

**Comment by chris1111** [comment]
Try to change the **DSDT.aml** in EFI/CLOVER/ACPI/patched
attaching DSDThere
[DSDT.aml.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator/files/5939034/DSDT.aml.zip)

**Comment by nello16** [comment]
Hi Chris,
it _works_, works, **works**!! You are great!!
Choose a net, insert pwd and go to internet!!
There are some issue: if I push button on the top the wifi has been disabled and there no way to re-activate (the light is always orange). the icon is bordered but empty, if I click it I see the network list but if I choose one of them a pop up a message appears: "You can't connect to .... The network in unreachable ". It's like the push button works only to disable. after reboot the wifi works again: I will never touch the push button. 
The other issue is that the display looses the regulation of luminosity but acquire the "Rotation" of display (I don't remember before).
Finally during these tests I have encountered some freeze (with forced proweroff) and stuck after reboot (reboot again went right).

**Comment by chris1111** [comment]
Try this 😇
[DSDT.aml.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator/files/5939750/DSDT.aml.zip)

**Comment by nello16** [comment]
With this one the control bright is coming back but no more wifi and audio, in system preferences no device found. the wifi and audio icons is grayed.
![icons](https://user-images.githubusercontent.com/78387883/107157653-7fc33b00-6985-11eb-84fe-5f232844393f.png)

**Comment by chris1111** [comment]
Ok my fault use this one 
[DSDT.aml.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator/files/5939843/DSDT.aml.zip)

**Comment by nello16** [comment]
sorry Chris, after a reboot all works!!!
I've tried further 4 reboot (with power off and no) and everything works!!
great job!!
I don't consider the last DSDT or you want to make a test?

**Comment by chris1111** [comment]
> sorry Chris, after a reboot all works!!!
> I've tried further 4 reboot (with power off and no) and everything works!!
> great job!!
> I don't consider the last DSDT or you want to make a test?
Good
Yes you can test it backup the working one

**Comment by nello16** [comment]
using last DSDT wifi works (like audio) but there isn't bright control (there is the screen rotation control). So I think the best is the second last DSDT.
Remain to fix the card reader and bluetooth, but it is not so important (also if it's better they work :) )
Thanks for you work, let me know what I can do for you.
Finally just two things: I'm thinking to upgrade RAM (4->8GB) and CPU (i3->i5): do you think there will be some issue? Will I have to change something else?

**Comment by chris1111** [comment]
OK
Upgrade cpu and ram you net need to change anything

**Comment by spn0381** [comment]
I'm trying to install Catalina on a HP Probook 10.15.7 from scratch. I'm following your suggestion and I've:

- installed Catalina 10.15.7 from scratch
- done every update via wifi
- only after all the update, Install the "HP-ProBook-EliteBook-macOS.pkg"
- without rebooting install the "Legacy-Video-patch" but the installer fails reporting this error: "Runtime Script Error - AppleEvent timed out,"

I have to reboot and after I obtain the Apple screen of death "your computer restarted because of a problem ....", I reboot, and the hp loop.

even starting with the clover on the usb key OSX Loop

any Idea about what I'm doing wrong?

[Imgur](https://i.imgur.com/YMgWCJRt.jpg)

**Comment by Wenfei0319** [comment]
Hi,Nello16.I trying to installed Catalina on my noto book,but many failing.
If you are not busy.can you send the EFI of Catalina to me?

aha001@yeah.net
This is my Email address.
Thanks.

**Comment by Wenfei0319** [comment]
@nello16
