### ISSUE TITLE
error with build create install media 

### ISSUE THREAD

**Issue by eljartu** [chris1111/HP-Probook-EliteBook-Package-Creator#6]
Thanks for your work chris, I need help with this, I downloaded the file several times and I still have the same error:

Build Create Install Media
/dev/disk3          	GUID_partition_scheme          	
/dev/disk3s1        	Apple_HFS                      	/Volumes/HP-ProBook-EliteBook-macOS
= = = = = = = = = = = = = = = = = = = = = = = = =  
Create HP ProBook EliteBook Installer 
= = = = = = = = = = = = = = = = = = = = = = = = =  
Create Install Media HP Laptop.applescript:37: error: A identifier can’t go after this identifier. (-2740)
cp: Create Install Media HP Laptop.app/Contents/Resources: No such file or directory
cp: Create Install Media HP Laptop.app/Contents/Resources: No such file or directory
cp: Create Install Media HP Laptop.app/Contents/Resources: No such file or directory
cp: Create Install Media HP Laptop.app/Contents/Resources: No such file or directory
cp: description.rtfd: unable to copy extended attributes to Create Install Media HP Laptop.app/Contents/Resources: No such file or directory
cp: Create Install Media HP Laptop.app/Contents/Resources/Capture.png: No such file or directory
cp: Create Install Media HP Laptop.app/Contents/Resources/TXT.rtf: No such file or directory
cp: utimes: Create Install Media HP Laptop.app/Contents/Resources: No such file or directory
cp: chown: Create Install Media HP Laptop.app/Contents/Resources: No such file or directory
cp: chmod: Create Install Media HP Laptop.app/Contents/Resources: No such file or directory
cp: chflags: Create Install Media HP Laptop.app/Contents/Resources: No such file or directory
cp: description.rtfd: unable to copy ACL to Create Install Media HP Laptop.app/Contents/Resources: No such file or directory
cp: Create Install Media HP Laptop.app/Contents/Resources: No such file or directory
Unable to set file icon
mv: rename ./Create Install Media HP Laptop.app to /Users/qp/Desktop/Create Install Media HP Laptop.app: No such file or directory

= = = = = = = = = = = = = = = = = = = = = = = = = 
Create Install Media HP Laptop.app completed
Downloading Clover installer, wait. . . .
= = = = = = = = = = = = = = = = = = = = = = = = =  
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   608    0   608    0     0    204      0 --:--:--  0:00:02 --:--:--   204
100 63.2M  100 63.2M    0     0  1605k      0  0:00:40  0:00:40 --:--:-- 2725k
= = = = = = = = = = = = = = = = = = = = = = = = =  
Desktop ➤ Create Install Media HP Laptop.app
Completed Done!   
= = = = = = = = = = = = = = = = = = = = = = = = =  
"disk3" unmounted.
"disk3" ejected.
 

Tye any key to return to menue

**Comment by chris1111** [comment]
I don't know what wrong with your system
