### ISSUE TITLE
Installation of macOS Mojave on HP ProBook Series 6 Laptops

### ISSUE THREAD

**Issue by olakunle4luv** [chris1111/HP-Probook-EliteBook-Package-Creator#63]
I would appreciate if you can continue the update on HP series 6 laptop. I don't mind paying you for the work process. I really appreciate your hard work over this project. There are more of my customer requesting for this services on the HP series 6 Laptop. i am expecting your feedback on this. Thanks

**Comment by chris1111** [comment]
No sorry the decision is clear
