### ISSUE TITLE
<Battery issues> Battery charging very slow on Catalina HP elitebook 8470p.

### ISSUE THREAD

**Issue by noocool** [chris1111/HP-Probook-EliteBook-Package-Creator#64]
Hi chris! 
First, thank you so much for your wonderful package. My hackintosh work nearly perfectly by following your guide.
But I have a problem with my laptop. The battery charging slowly even I shut down it. It took me about 5-6 hours to get full battery. How can I do to fix this problem? Please tell me! Thank you so much!

About my laptop:
HP Elitebook 8470p
3rd Generation Intel Core i5-3320M (2.60 GHz, 3MB L3 cache, 35 W, 2 cores)
HD 4000, 1366x768
OS version: Catalina 10.15.7

**Comment by chris1111** [comment]
I not use Catalina since the first Beta of Big Sur so its hard to help here
https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC
Do you try to find an Update kext of ACPIBatteryManager.kext?

**Comment by noocool** [comment]
I use 1.90.1 ACPIBatteryManager.kext  and I think it is the lastest kext. I searched this problem on Google but I didn't see any problem like this. I just have installed fresh Catalina for few day for requirement of some app.

**Comment by noocool** [comment]
Should I install Big Sur? I think it's not stable to use.
How about my laptop? Is this suitable to install Big Sur like a real mac?

**Comment by chris1111** [comment]
If you want BS you need follow the guide of Big Sur
Do you try on Catalina changing ACPIBattery for SMCBatteryManager.kext ?

**Comment by noocool** [comment]
Oh, I will try and test this. I think the problem can be caused by my charger, my battery or not. I will check all case and notify you later.
