### ISSUE TITLE
Unable to create HighSierra Media to use on HP 2560p

### ISSUE THREAD

**Issue by luknetcompany** [chris1111/HP-Probook-EliteBook-Package-Creator#65]
Hi Chris, thanks for this nice tool. Does it still work?

I am having issues creating the USB media. I first tried by Disabling the Gatekeep on a macbook pro running Catalina, and using a 16GB Drive (I have two of them and got the same issue). Then I tried using a Hackintosh also running Catalina, by first disabling SIP from config.plist using clover configurator. The process on both computers seems to get stuck at around 70% progress for about 15-20 minutes maybe, then it  resulted in an error saying something like:

**Erasing Disk: 0%.....10%.....20%.....30%....100%....IA app name cookie write failed. The copy of the installer app failed.** Please check attached screenshot for more details. Is there something that I am missing?

![WhatsApp Image 2021-06-15 at 3 33 34 PM](https://user-images.githubusercontent.com/85764764/122062900-1b5f2f00-cdf0-11eb-861e-9ec0311fe72e.jpeg)

**Comment by chris1111** [comment]
probably SIP is not fully disable also you have to reset NVRAM I think
