### ISSUE TITLE
Cannot Adjust Brightness for Probook 6460b

### ISSUE THREAD

**Issue by arno608rw** [chris1111/HP-Probook-EliteBook-Package-Creator#7]
Cannot Adjust Brightness for Probook 6460b, intel Graphics 3000 3MB + 1024x768

**Comment by chris1111** [comment]
> Cannot Adjust Brightness for Probook 6460b, intel Graphics 3000 3MB + 1024x768

which macOS ? 
Upload your EFI Folder here please

**Comment by arno608rw** [comment]
Mojeve 
EFI.zip
https://www.dropbox.com/s/64haknj2vsp1pgv/EFI.zip?dl=0

**Comment by chris1111** [comment]
> Mojeve
> EFI.zip
> https://www.dropbox.com/s/64haknj2vsp1pgv/EFI.zip?dl=0

Try this command in terminal

sudo kextcache -system-prelinked-kernel
sudo kextcache -system-caches

Then Reboot your system

**Comment by arno608rw** [comment]
Thank. I will try when I get home.

**Comment by chris1111** [comment]
> Thank. I will try when I get home.

If not working Try fresh Install of macOS Mojave with latest release
https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator/releases/tag/V2
Do not forget to format your SSD as in the video

**Comment by arno608rw** [comment]
not work. If reinstall with latest release. I can select path HD 3000 Mojeve? because previous version, I selected not boot

**Comment by arno608rw** [comment]
Sorry, I am not good at English

> > not work. If reinstall with latest release. I can select path HD 3000 Mojeve? because previous version, I selected not boot
> 
> please be clearer I do not understand ?
Sorry, I am not good at English

> > not work. If reinstall with latest release. I can select path HD 3000 Mojeve? because previous version, I selected not boot
> 
> please be clearer I do not understand ?
Sorry, I am not good at English

**Comment by chris1111** [comment]
I am put another release in few minutes with a different approach for Patch Intel HD 3000
please test and report
thanks

**Comment by arno608rw** [comment]
Thank, I will test tomorrow and report to you

**Comment by chris1111** [comment]
> Thank, I will test tomorrow and report to you

Try fresh Install of macOS Mojave with latest release

See picture

![Modular Image Creation](https://i25.servimg.com/u/f25/18/50/18/69/screen66.png)
![Modular Image Creation](https://i25.servimg.com/u/f25/18/50/18/69/screen67.png)
![Modular Image Creation](https://i25.servimg.com/u/f25/18/50/18/69/screen68.png)

Hope that work

**Comment by arno608rw** [comment]
Wow!!!. It work with latest release. Thank you @chris1111 
![screen shot 2561-11-19 at 20 52 38](https://user-images.githubusercontent.com/3774145/48711225-83f5b900-ebbf-11e8-9504-9c9485698612.png)
![screen shot 2561-11-19 at 20 53 09](https://user-images.githubusercontent.com/3774145/48711231-8bb55d80-ebbf-11e8-8895-4dd6d15ad928.png)

**Comment by chris1111** [comment]
> Wow!!!. It work with latest release. Thank you @chris1111
> ![screen shot 2561-11-19 at 20 52 38](https://user-images.githubusercontent.com/3774145/48711225-83f5b900-ebbf-11e8-9504-9c9485698612.png)
> ![screen shot 2561-11-19 at 20 53 09](https://user-images.githubusercontent.com/3774145/48711231-8bb55d80-ebbf-11e8-8895-4dd6d15ad928.png)

Thank you for testing and sharing your experiences 
👋 I am really happy that's working finally for you 😃

**Comment by chris1111** [comment]
@arno608rw I was going to add you in the Credit
thanks

**Comment by chris1111** [comment]
Hi @arno608rw do you please test to create a USB with the latest create install media HP laptop
with your  6460B . Simply boot to the installer and let me known if that ok for the 6 series laptop

**Comment by arno608rw** [comment]
Hi @chris1111 It work but if I open VDO or youtube. It have horizontal line blink
![Screen Shot 2562-04-02 at 11 25 22](https://user-images.githubusercontent.com/3774145/55376316-19c02e00-553a-11e9-8581-8fe873935d13.png)
![Screen Shot 2562-04-02 at 11 14 17](https://user-images.githubusercontent.com/3774145/55376376-4ffdad80-553a-11e9-892a-60b83c298245.png)

**Comment by chris1111** [comment]
Hi this is a Graphics Glitch relate to HD 3000 
Try to ad **slide=0** on the boot args in the config.plist

**Comment by arno608rw** [comment]
> Hi @arno608rw do you please test to create a USB with the latest create install media HP laptop
> with your 6460B . Simply boot to the installer and let me known if that ok for the 6 series laptop

I test reinstall on latest create install [https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator/releases/download/V2/HP-Probook-EliteBook-Package-Creator.zip](HP-Probook-EliteBook-Package-Creator) is OK. but after install path HD 3000 Mojeve It's not work (black screen)

**Comment by chris1111** [comment]
Ok wait my update i have to change the patch for 10.14 4
I will update tonight. When I am back to home

**Comment by chris1111** [comment]
If the patch not working its the end of patching HD 3000 on Mojave because this is the only solution

**Comment by chris1111** [comment]
If the patch not working on 10.14.4 its the end of patching HD 3000 on Mojave because this is the only solution

Let me see If another solution exist or use install MacOS Mojave.app 10.14.3

**Comment by chris1111** [comment]
Ok please try new Release Update
https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator/releases/tag/V2
Let me know if that work, thanks

**Comment by arno608rw** [comment]
> Ok please try new Release Update
> https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator/releases/tag/V2
> Let me know if that work, thanks

test on 10.14.4 ?

**Comment by chris1111** [comment]
> > Ok please try new Release Update
> > https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator/releases/tag/V2
> > Let me know if that work, thanks
> 
> test on 10.14.4 ?

Yes Download the latest  Install macOS Mojave.app
This  is 14.4.08

![Modular Image Creation](https://i25.servimg.com/u/f25/18/50/18/69/captu580.png)

**Comment by arno608rw** [comment]
Not work (black screen)
![IMG_7430](https://user-images.githubusercontent.com/3774145/55478068-e5856400-5644-11e9-84e7-04f77151e730.JPG)

**Comment by chris1111** [comment]
Try boot Inject Intel=false and telling me  if you are able to reach the desktop

**Comment by arno608rw** [comment]
I try Inject Intel=false it's same not work (black screen)
![IMG_7431](https://user-images.githubusercontent.com/3774145/55478352-b7ecea80-5645-11e9-8285-27ad9dbf58d1.JPG)

**Comment by chris1111** [comment]
Ok wait I post in couple minute a new package to try
thanks

**Comment by chris1111** [comment]
Ok try fresh install of Mojave and for post Install HD 3000  use this package
[Fix Graphics HD 3000 Mojave.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator/files/3038635/Fix.Graphics.HD.3000.Mojave.zip)

**Comment by arno608rw** [comment]
it's same not work (black screen). I try fresh 14.3.2 

![IMG_7432](https://user-images.githubusercontent.com/3774145/55482762-6d706b80-564f-11e9-9f49-6ecc6ceeb3fd.JPG)

**Comment by chris1111** [comment]
Ok please test this package on fresh install


[Fix Graphics HD 3000 Mojave.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator/files/3038920/Fix.Graphics.HD.3000.Mojave.zip)

**Comment by arno608rw** [comment]
> Ok please test this package on fresh install
> 
> [Fix Graphics HD 3000 Mojave.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator/files/3038920/Fix.Graphics.HD.3000.Mojave.zip)

OK I will test on 10.14.4

**Comment by chris1111** [comment]
> > Ok please test this package on fresh install
> > [Fix Graphics HD 3000 Mojave.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator/files/3038920/Fix.Graphics.HD.3000.Mojave.zip)
> 
> OK I will test on 10.14.4

Thanks for testing 
 if this not work; the solution for HD 3000 is break on 10.14.4

**Comment by arno608rw** [comment]
> > > Ok please test this package on fresh install
> > > [Fix Graphics HD 3000 Mojave.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator/files/3038920/Fix.Graphics.HD.3000.Mojave.zip)
> > 
> > 
> > OK I will test on 10.14.4
> 
> Thanks for testing
> if this not work; the solution for HD 3000 is break on 10.14.4

Not work.

**Comment by chris1111** [comment]
> > > > Ok please test this package on fresh install
> > > > [Fix Graphics HD 3000 Mojave.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator/files/3038920/Fix.Graphics.HD.3000.Mojave.zip)
> > > 
> > > 
> > > OK I will test on 10.14.4
> > 
> > 
> > Thanks for testing
> > if this not work; the solution for HD 3000 is break on 10.14.4
> 
> Not work.

If you find a working solution, please post result here
Thanks for the test I am really appreciate

**Comment by arno608rw** [comment]
V2 work 10.14.3.

**Comment by chris1111** [comment]
I know 
Thanks

**Comment by chris1111** [comment]
I have another solution for HD 3000 Mojave 10.14.4
Do you test please

**Comment by arno608rw** [comment]
> I have another solution for HD 3000 Mojave 10.14.4
> Do you test please
> 
> Here the package to test on fresh install Mojave 10.14.4
> [Download ➤ Fix Graphics HD 3000 Mojave-10.14.4 ](https://www.hackintosh-montreal.com/download.forum?id=4333)

OK. I will testing

**Comment by chris1111** [comment]
> > I have another solution for HD 3000 Mojave 10.14.4
> > Do you test please
> > Here the package to test on fresh install Mojave 10.14.4
> > [Download ➤ Fix Graphics HD 3000 Mojave-10.14.4 ](https://www.hackintosh-montreal.com/download.forum?id=4333)
> 
> OK. I will test.... sorry I forgot the device at work. I can test on Monday

Ok Thank you I will see your answer of test Monday 💻 😃

**Comment by chris1111** [comment]
Ok I test my self on my PC Dell Optiplex with Intel HD 3000 
Works perfect 
 [NEW package available HERE ➣](https://www.hackintosh-montreal.com/download.forum?id=4336)
Please test on HP Laptop, Download the new package build  
![Modular Image Creation](https://i25.servimg.com/u/f25/18/50/18/69/captu585.png)
![Modular Image Creation](https://i.servimg.com/u/f25/18/50/18/69/screen22.jpg)
![Modular Image Creation](https://i.servimg.com/u/f25/18/50/18/69/screen23.jpg)

**Comment by chris1111** [comment]
Please read my previous message 😇 🙏

**Comment by arno608rw** [comment]
> Please read my previous message 😇 I need confirmation test 🙏

OK I will test last Release

**Comment by arno608rw** [comment]
Hi I will test the next day.I'm busy today

**Comment by arno608rw** [comment]
I testing .....
![IMG_7489](https://user-images.githubusercontent.com/3774145/55864487-c9cf1000-5ba6-11e9-8b08-b9055d9ad1e7.JPG)

**Comment by arno608rw** [comment]
Good news... It's work!!!!!!!!!!!!!!!!!! thanks my friends @chris1111 
![IMG_7491](https://user-images.githubusercontent.com/3774145/55865118-f59ec580-5ba7-11e9-9c0e-e17eab4568a0.JPG)

**Comment by chris1111** [comment]
Thank you 
The V2 or the package ?

**Comment by arno608rw** [comment]
> Thank you
> The V2 or the package ? Ok I see its the built package so I will Update the release NOW !!!!!!! 🤝
> 😎

YES

**Comment by chris1111** [comment]
> > Thank you
> > The V2 or the package ? Ok I see its the built package so I will Update the release NOW !!!!!!! 🤝
> > 😎
> 
> YES V2 and install package in share drive https://drive.google.com/file/d/1or2SMuYVPLliATm5sO0jQeaEHFFwWS0N/view?usp=sharing

Thank you Verry much really appreciate again your contribution 😀
Release V2 is updating 💻⚙️

**Comment by chris1111** [comment]
Hi @arno608rw 
New release update support Intel HD 3000 macOS Mojave 10.14.5
Please test when you have time👍🏻
![Modular Image Creation](https://i25.servimg.com/u/f25/18/50/18/69/captu648.png)


My test result
![Modular Image Creation](https://i25.servimg.com/u/f25/18/50/18/69/untitl13.png)

**Comment by arno608rw** [comment]
Update or clean install

**Comment by chris1111** [comment]
> Update or clean install

Clean Install because I don't think Update will work

**Comment by chris1111** [comment]
[💻 ](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator/issues/7#issuecomment-493171888)

**Comment by chris1111** [comment]
> Update or clean install

Clean Install because I don't think Update will work
Clean install With the latest install macOS Mojave.app from App Store

**Comment by arno608rw** [comment]
Sorry, I can't test because ssd damaged. I will test next time

**Comment by chris1111** [comment]
> Sorry, I can't test because ssd damaged. I will test next time

ok thank you

**Comment by chris1111** [comment]
Today its confirming by a friend Intel HD 3000 works in 10.14.5
![Modular Image Creation](https://i25.servimg.com/u/f25/18/50/18/69/captu674.png)
![Modular Image Creation](https://i25.servimg.com/u/f25/18/50/18/69/captu675.png)

**Comment by arno608rw** [comment]
Good job

**Comment by arno608rw** [comment]
It work. 
![Screen Shot 2562-06-25 at 10 54 27](https://user-images.githubusercontent.com/3774145/60068333-6df13d80-9738-11e9-8ad2-d5929c459381.png)

but black line screen on open youtube or videos
![Screen Shot 2562-06-25 at 10 59 12](https://user-images.githubusercontent.com/3774145/60068392-c294b880-9738-11e9-881b-321fb6cb8535.png)

**Comment by chris1111** [comment]
DID you install adobe flash player for Mac

**Comment by chris1111** [comment]
??

**Comment by arno608rw** [comment]
> ??

Yes, I have

**Comment by chris1111** [comment]
> > ??
> 
> Yes, I have

Try to add **slide=0** in boot ergs of config.plist

**Comment by arno608rw** [comment]
work
