### ISSUE TITLE
7th Gen Acer Aspire ES1-572-321g

### ISSUE THREAD

**Issue by Hiba-Khani** [chris1111/HP-Probook-EliteBook-Package-Creator#9]
Dear CHRIS1111

Request for DSDT Full Patching. my origin.zip Attached
my Specs 
CPU      (i3 7100U)
Graphics  intel HD 620
Wifi   BCM94352Z M.2
[origin.zip](https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator/files/2707705/origin.zip)

for more Guide Thats my Laptop Hardware Page
https://snlookup.com/acer-aspire-es1-572-notebook-nx-gkqaa-001-p39424#ffs-tabbed-11

Thanks and your work is Brilliant.

**Comment by chris1111** [comment]
thanks for comment but I am not response to this, this GitHub  page is for the HP ProBook
